# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"H\n\teventData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\x12\n\x05money\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_money\"8\n\x0f\x43ustomerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x19\n\x05\x65vent\x18\x02 \x01(\x0b\x32\n.eventData\"c\n\x0cresponseData\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x13\n\x06result\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x62\x61lance\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\t\n\x07_resultB\n\n\x08_balance2K\n\x17\x42\x61nkTransactionsService\x12\x30\n\x0bMsgDelivery\x12\x10.CustomerRequest\x1a\r.responseData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EVENTDATA']._serialized_start=17
  _globals['_EVENTDATA']._serialized_end=89
  _globals['_CUSTOMERREQUEST']._serialized_start=91
  _globals['_CUSTOMERREQUEST']._serialized_end=147
  _globals['_RESPONSEDATA']._serialized_start=149
  _globals['_RESPONSEDATA']._serialized_end=248
  _globals['_BANKTRANSACTIONSSERVICE']._serialized_start=250
  _globals['_BANKTRANSACTIONSSERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
